services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - node_modules:/workspace/client/node_modules
    working_dir: /workspace/client
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  node_modules: